
from fpdf import FPDF
from datetime import datetime
from typing import Dict, Any, List
import io

class EvidenceReport(FPDF):
    def __init__(self, username: str, platform: str):
        super().__init__()
        self.username = username
        self.platform = platform
        self.set_auto_page_break(auto=True, margin=15)
        self.add_page()
        
    def header(self):
        self.set_font("helvetica", "B", 20)
        self.cell(0, 10, f"Cheat Detection Report: {self.username}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("helvetica", "I", 10)
        self.cell(0, 10, f"Generated by ChessGuard on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(10)

    def chapter_title(self, title):
        self.set_font("helvetica", "B", 14)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def chapter_body(self, body):
        self.set_font("helvetica", "", 11)
        self.multi_cell(0, 6, body)
        self.ln()
        
    def add_game_evidence(self, game_data: Dict[str, Any]):
        self.set_font("helvetica", "B", 12)
        game_title = f"Game: {game_data.get('white')} vs {game_data.get('black')}"
        self.cell(0, 10, game_title, new_x="LMARGIN", new_y="NEXT")
        
        self.set_font("helvetica", "", 10)
        self.cell(0, 6, f"URL: {game_data.get('url')}", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 6, f"Result: {game_data.get('result')}", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 6, f"Suspicion Score: {game_data.get('suspicion_score')}", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)
        
        # Flags
        flags = game_data.get('flags', [])
        if flags:
            self.set_font("helvetica", "B", 10)
            self.cell(0, 6, "Detection Flags:", new_x="LMARGIN", new_y="NEXT")
            self.set_font("courier", "", 9)
            for flag in flags:
                self.cell(0, 5, f" - {flag}", new_x="LMARGIN", new_y="NEXT")
            self.ln(2)
            
        # V2 Metrics
        self.set_font("helvetica", "B", 10)
        self.cell(0, 6, "Advanced Metrics:", new_x="LMARGIN", new_y="NEXT")
        self.set_font("helvetica", "", 10)
        
        cols = [
            ("Sniper Gap", f"{game_data.get('sniper_gap', 0):.1%}"),
            ("Critical Accuracy", f"{game_data.get('critical_accuracy', 0):.1%}"),
            ("Engine Agmt", f"{game_data.get('engine_agreement', 0):.1%}")
        ]
        
        for name, val in cols:
             self.cell(50, 6, f"{name}: {val}", border=1)
        self.ln(10)

def generate_report(username: str, platform: str, games: List[Dict[str, Any]]) -> bytes:
    pdf = EvidenceReport(username, platform)
    
    # Summary Section
    pdf.chapter_title("Executive Summary")
    high_risk_games = sum(1 for g in games if g.get('suspicion_score', 0) > 0.8)
    avg_score = sum(g.get('suspicion_score', 0) for g in games) / len(games) if games else 0
    
    summary = (
        f"This report outlines potential fair play violations for player {username}.\n"
        f"Total Games Analyzed: {len(games)}\n"
        f"High Risk Games (>80%): {high_risk_games}\n"
        f"Average Suspicion Score: {avg_score:.2f}\n"
    )
    pdf.chapter_body(summary)
    
    # Detailed Evidence
    pdf.chapter_title("Detailed Game Evidence")
    for game in games:
        if game.get('suspicion_score', 0) > 0.5 or game.get('flags'):
            pdf.add_game_evidence(game)
            
    return pdf.output()
